runtime: java11
#entrypoint: java -Xmx64m -jar HomeGaeFlexJ11Example-0.0.1-SNAPSHOT.jar
env: flex
service: default
manual_scaling:
  instances: 1
handlers:
  - url: /.*
    script: this field is required, but ignored